import { useState } from 'react';
import { ArrowRight, Banknote, Check, CreditCard, MessageCircle, Plus, ShieldCheck, Wallet } from 'lucide-react';

export const paymentMethods = [
  { id: 'stripe', name: 'Stripe', mark: 'S', color: '#635bff', description: 'Cards through Stripe', hint: 'Integration required' },
  { id: 'venmo', name: 'Venmo', mark: 'V', color: '#008cff', description: 'Arrange payment with your seller', hint: 'Pay outside Dorm.io', placeholder: '@your-username' },
  { id: 'paypal', name: 'PayPal', mark: 'P', color: '#0070ba', description: 'Arrange payment with your seller', hint: 'Pay outside Dorm.io', placeholder: 'Your PayPal email' },
  { id: 'cashapp', name: 'Cash App', mark: '$', color: '#087f3f', description: 'Arrange payment with your seller', hint: 'Pay outside Dorm.io', placeholder: '$yourcashtag' },
  { id: 'cash', name: 'Cash at pickup', mark: 'cash', color: '#997140', description: 'Pay the seller in person', hint: 'No account needed' },
  { id: 'wallet', name: 'Dorm.io wallet', mark: 'wallet', color: '#785ef0', description: 'Try checkout with demo funds', hint: 'Demo balance' },
];
export const methodName = id => paymentMethods.find(method => method.id === id)?.name || 'Dorm.io wallet';
export const formatMoney = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(value);
export function PaymentMark({ method }) { return <span className="provider-mark" style={{ background: method.color }}>{method.mark === 'cash' ? <Banknote size={22} /> : method.mark === 'wallet' ? <Wallet size={21} /> : method.mark}</span>; }
export function PaymentPicker({ value, onChange }) {
  return <fieldset className="payment-picker"><legend>How would you like to pay?</legend>{paymentMethods.map(method => <label className={value === method.id ? 'selected' : ''} key={method.id}><input type="radio" name="checkout-method" value={method.id} checked={value === method.id} onChange={() => onChange(method.id)} /><PaymentMark method={method} /><span><strong>{method.name}</strong><small>{method.hint}</small></span></label>)}</fieldset>;
}

export function PaymentCheckout({ selected, method, setMethod, balance, error, buyItem, paymentDone, startChat, closeModal, navigate, formatMoney: displayMoney = formatMoney }) {
  const external = method !== 'wallet';
  if (paymentDone) return <div className="success-content"><div className="success-icon"><Check size={36} /></div><h2 id="modal-title">{external ? 'Reserved. Plan your pickup!' : 'Good find. It’s yours!'}</h2><p>{external ? `Your ${methodName(method)} payment of ${displayMoney(selected.price)} is still due. Message ${selected.seller} to agree on payment and pickup. No money has moved in Dorm.io.` : `Your demo payment of ${displayMoney(selected.price)} is complete. Message ${selected.seller} to arrange a pickup.`}</p><div className="order-summary"><img src={selected.image} alt="" /><div><strong>{selected.title}</strong><span>{external ? `${methodName(method)} · Payment pending` : 'Paid with Dorm.io demo wallet'}</span></div></div><button className="primary full-width" onClick={() => startChat(selected)}>Arrange a pickup <MessageCircle size={17} /></button><button className="text-button" onClick={() => { closeModal(); navigate('My wallet'); }}>View wallet activity</button></div>;
  return <div className="modal-body"><div className="eyebrow">VIRGINIA TECH · CHECKOUT</div><h2 id="modal-title">Make a good find yours.</h2><div className="order-summary"><img src={selected.image} alt="" /><div><strong>{selected.title}</strong><span>Sold by {selected.seller}</span></div><strong>{displayMoney(selected.price)}</strong></div><PaymentPicker value={method} onChange={setMethod} /><div className="payment-method"><Wallet size={21} /><div><strong>{methodName(method)}</strong><small>{method === 'wallet' ? `Available balance: ${displayMoney(balance)}` : method === 'stripe' ? 'Stripe checkout is not connected yet.' : method === 'cash' ? 'Pay the seller in person at campus pickup.' : 'Agree on the seller’s payment details in Messages.'}</small></div></div><div className="checkout-totals"><div><span>Campus pickup</span><span>Free</span></div><div className="total"><strong>{external ? 'Due to seller' : 'Total'}</strong><strong>{displayMoney(selected.price)}</strong></div></div>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary full-width" onClick={buyItem} disabled={method === 'stripe' || (method === 'wallet' && selected.price > balance)}>{method === 'stripe' ? 'Stripe integration required' : method === 'wallet' ? `Pay ${displayMoney(selected.price)}` : method === 'cash' ? 'Reserve · Pay cash at pickup' : `Reserve · Pay with ${methodName(method)}`}</button>{method === 'wallet' && selected.price > balance && <p className="form-error">Insufficient demo funds. Choose another payment method.</p>}<p className="checkout-note">{method === 'wallet' ? 'Demo funds only. No real money is charged.' : 'Reservations are not payment confirmations. Arrange payment with your seller.'}</p></div>;
}

export function AddCredits({ onDeposit, formatMoney: displayMoney = formatMoney }) {
  const providers = paymentMethods.filter(method => ['stripe', 'venmo', 'paypal', 'cashapp'].includes(method.id));
  const [provider, setProvider] = useState('stripe');
  const [amount, setAmount] = useState(25);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const submit = async event => {
    event.preventDefault();
    setSubmitting(true);
    setError('');
    try {
      const checkoutId = `test_${crypto.randomUUID().replaceAll('-', '')}`;
      await onDeposit({ amount, provider, checkoutId });
    } catch (depositError) {
      setError(depositError.message || 'The test deposit could not be completed.');
      setSubmitting(false);
    }
  };
  return <form className="modal-body add-credits-form" onSubmit={submit}><div className="eyebrow">NESSIE · TEST MODE</div><h2 id="modal-title">Add credits to your wallet.</h2><p>Simulate buying marketplace credits through a test payment provider. No real payment account is contacted or charged.</p><fieldset className="payment-picker"><legend>Test payment method</legend>{providers.map(method => <label className={provider === method.id ? 'selected' : ''} key={method.id}><input type="radio" name="deposit-provider" value={method.id} checked={provider === method.id} onChange={() => setProvider(method.id)} /><PaymentMark method={method} /><span><strong>{method.name}</strong><small>Test purchase</small></span></label>)}</fieldset><fieldset className="credit-amounts"><legend>Choose an amount</legend>{[10, 25, 50, 100].map(value => <button className={amount === value ? 'selected' : ''} type="button" onClick={() => setAmount(value)} key={value}>{displayMoney(value)}</button>)}</fieldset><div className="test-payment-note"><ShieldCheck size={18} /><span><strong>Test checkout only</strong><small>The backend will record a real deposit in the Nessie simulation account.</small></span></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary full-width" disabled={submitting}>{submitting ? 'Adding credits…' : `Add ${displayMoney(amount)} with test ${methodName(provider)}`}</button></form>;
}

export default function CampusWallet({ balance, profile, transactions, preferences, setPreferences, setModal, setSetupMethod, navigate, cancelReservation, contactSeller, walletAccount, walletConnectionError, formatMoney: displayMoney = formatMoney }) {
  const choose = id => setPreferences(current => ({ ...current, preferred: id }));
  return <><div className="page-heading"><div><div className="eyebrow">VIRGINIA TECH · CAMPUS PAYMENTS</div><h1>Your wallet. Your way to pay.</h1><p>Choose a payment method before your next campus find.</p></div></div><div className="wallet-layout"><div className="wallet-card"><span><Wallet size={22} /> Dorm.io wallet</span><p>Available demo balance</p><h2>{displayMoney(balance)}</h2><div><span>{profile.name}</span><span>{walletAccount ? 'Nessie connected' : 'Local fallback'}</span></div><button className="wallet-add-button" onClick={() => setModal('addCredits')}><Plus size={16} /> Add test credits</button>{walletConnectionError && <small className="wallet-connection-error">{walletConnectionError}</small>}</div><div className="wallet-explainer"><CreditCard size={27} /><h3>Pay online or at pickup.</h3><p>Use a simulated Stripe, Venmo, PayPal, or Cash App purchase to add credits. The payment is fake, but the resulting deposit is recorded in the Nessie sandbox.</p><span className="demo-note">No real money or payment credentials are used.</span></div></div>
  <section className="panel provider-panel"><div className="provider-heading"><h2>Payment methods</h2><span>Preferred: {methodName(preferences.preferred)}</span></div><div className="provider-grid">{paymentMethods.map(method => <article className={`provider-card ${preferences.preferred === method.id ? 'preferred' : ''}`} key={method.id}><div className="provider-title"><PaymentMark method={method} /><div><h3>{method.name}</h3><small>{method.hint}</small></div>{preferences.preferred === method.id && <Check size={17} />}</div><p>{method.description}</p>{preferences.handles[method.id] && <small className="provider-handle">Your saved detail: {preferences.handles[method.id]}</small>}<div className="provider-actions"><button className="text-button" disabled={preferences.preferred === method.id} onClick={() => choose(method.id)} aria-label={`Prefer ${method.name}`}>{preferences.preferred === method.id ? 'Preferred' : 'Make preferred'}</button>{['stripe', 'venmo', 'paypal', 'cashapp'].includes(method.id) && <button className="text-button" onClick={() => { setSetupMethod(method.id); setModal('paymentSetup'); }}>{method.id === 'stripe' ? 'Connect Stripe' : 'Payment details'}<ArrowRight size={13} /></button>}</div></article>)}</div></section>
  <section className="panel"><h2>Payment activity <span className="count-pill">{transactions.length}</span></h2>{transactions.length ? transactions.map(tx => <div className={`payment-activity ${tx.kind === 'deposit' ? 'deposit-activity' : ''}`} key={tx.id}><PaymentMark method={paymentMethods.find(method => method.id === (tx.method || 'wallet')) || paymentMethods[5]} /><div><strong>{tx.title}</strong><small>{methodName(tx.method)} · {tx.seller} · {new Date(tx.date).toLocaleDateString()}</small><span className="status-pill">{tx.kind === 'deposit' ? 'Test credits deposited' : tx.status === 'cancelled' ? 'Cancelled' : tx.status === 'pending' ? tx.method === 'cash' ? 'Cash due at pickup' : 'Awaiting external payment' : 'Demo payment completed'}</span></div><strong>{tx.kind === 'deposit' ? '+' : ''}{displayMoney(tx.amount)}</strong>{tx.status === 'pending' && <div className="reservation-actions"><button className="text-button" onClick={() => contactSeller(tx.listingId)}><MessageCircle size={14} />Message seller</button><button className="text-button" onClick={() => cancelReservation(tx.id)}>Cancel reservation</button></div>}</div>) : <div className="empty-state"><Wallet size={34} /><h3>Your next good find starts here.</h3><p>Choose a payment method, then find something you love.</p><button className="primary" onClick={() => navigate('Explore')}>Explore listings <ArrowRight size={16} /></button></div>}</section></>;
}

export function PaymentSetup({ methodId, preferences, save, closeModal }) {
  const method = paymentMethods.find(item => item.id === methodId);
  const [handle, setHandle] = useState(preferences.handles[methodId] || '');
  if (methodId === 'stripe') return <div className="modal-body"><PaymentMark method={method} /><h2 id="modal-title">Connect with Stripe</h2><p>Stripe Connect is the integration for marketplace sellers. Dorm.io needs server-side onboarding and checkout before accounts can be connected.</p><div className="payment-explanation"><strong>Not connected</strong><p>This demo cannot authorize a Stripe account or charge a card. No payment credentials are collected here.</p></div><a className="primary full-width" href="https://docs.stripe.com/connect" target="_blank" rel="noreferrer">Stripe Connect setup <ArrowRight size={16} /></a><button className="secondary full-width" onClick={closeModal}>Back to wallet</button></div>;
  return <form className="modal-body account-panel" onSubmit={event => { event.preventDefault(); save(methodId, handle.trim()); }}><PaymentMark method={method} /><h2 id="modal-title">Your {method.name} details</h2><p>Save your own payment identifier for reference. This does not connect or verify an account, and it is not the seller’s payment destination.</p><div className="account-fields"><label>{method.name === 'PayPal' ? 'PayPal email' : `${method.name} username`}<input value={handle} onChange={event => setHandle(event.target.value)} type={methodId === 'paypal' ? 'email' : 'text'} maxLength={100} placeholder={method.placeholder} aria-label={`${method.name} payment detail`} /></label></div><div className="account-save-row"><button type="button" className="secondary" onClick={closeModal}>Cancel</button><button className="primary">Save payment details</button></div><small className="account-local-note">Saved on this device. Leave blank to remove.</small></form>;
}
