import { useEffect, useRef } from 'react';
import { ArrowRight, Bell, CheckCircle2, Gift, Heart, Home, Leaf, MapPin, MessageCircle, Search, ShieldCheck, Smartphone, Wallet, X, Moon, Sun } from 'lucide-react';
import { figmaImage } from '../figmaAssets';

export const campusCategories = [
  ['All finds', '⚡️ All Campus'], ['Textbooks', '📚 Textbooks'], ['Electronics', '💻 Electronics'],
  ['Furniture', '🛋️ Furniture'], ['Clothing & more', '🧥 Clothing & Fits'],
  ['Dorm essentials', '🍿 Dorm Essentials'], ['Free Stuff', '🎁 Free Stuff'],
];
const price = value => value === 0 ? 'FREE' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(value);

export function Brand({ onClick }) {
  return <button className="dorm-brand" onClick={onClick} aria-label="Dorm.io home"><span><Home size={24} strokeWidth={2.7} /></span>Dorm.io</button>;
}

export function SiteHeader({ search, setSearch, page, navigate, openSell, setModal, savedCount, profile, theme, toggleTheme }) {
  const searchRef = useRef(null);
  useEffect(() => {
    const shortcut = event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); searchRef.current?.focus(); } };
    window.addEventListener('keydown', shortcut);
    return () => window.removeEventListener('keydown', shortcut);
  }, []);
  return <header className="dorm-header"><div className="dorm-header-inner">
    <Brand onClick={() => navigate('Explore')} />
    <label className="dorm-search"><Search size={20} /><input ref={searchRef} aria-label="Search marketplace" placeholder="Search textbooks, mini fridges, fits, free stuff..." value={search} onChange={event => { if (page !== 'Explore') navigate('Explore'); setSearch(event.target.value); }} />{search ? <button aria-label="Clear search" onClick={() => setSearch('')}><X size={16} /></button> : <kbd>⌘ K</kbd>}</label>
    <div className="dorm-header-actions"><button className="primary post-item" onClick={openSell}>+ Post Item</button><button className="dorm-icon theme-toggle" aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'} title={theme === 'dark' ? 'Light mode' : 'Dark mode'} onClick={toggleTheme}>{theme === 'dark' ? <Sun size={20} /> : <Moon size={20} />}</button><button className="dorm-icon" aria-label="Notifications" onClick={() => setModal('notifications')}><Bell size={21} /><i /></button><button className="dorm-user" aria-label="Open profile settings" onClick={() => setModal('profile')}><img src={profile.avatar} alt="Your profile" /><span><strong>{profile.name}</strong><small>{profile.campus} {profile.year}</small></span></button></div>
  </div><nav className="dorm-account-nav" aria-label="Your marketplace">{[['Explore', Home], ['Saved items', Heart], ['Messages', MessageCircle], ['My listings', Gift], ['My wallet', Wallet]].map(([name, Icon]) => <button key={name} onClick={() => navigate(name)} className={page === name ? 'active' : ''}><Icon size={14} />{name}{name === 'Saved items' && savedCount > 0 && <span>{savedCount}</span>}</button>)}</nav></header>;
}

export function CategoryNav({ category, onCategory }) {
  return <nav className="dorm-categories dorm-container" aria-label="Listing categories">{campusCategories.map(([value, label]) => <button key={value} className={category === value ? 'active' : ''} onClick={() => onCategory(value)}>{label}</button>)}</nav>;
}

export function ProductCard({ item, saved, toggleSave, openDetail }) {
  const imageSpeech = `Image of ${item.title}, a ${item.condition.toLowerCase()} ${item.category.toLowerCase()} listing. ${item.description}`;
  return <article className="dorm-product product-card" data-speech={`${item.title}. ${price(item.price)}. ${item.condition} condition. Sold by ${item.seller}.`}><div className="dorm-product-image"><button className="dorm-image-button" data-speech={`${imageSpeech} Select to view listing details.`} aria-label={`View ${item.title}`} onClick={() => openDetail(item)}><img src={item.image} alt={item.title} data-speech={imageSpeech} loading="lazy" /></button><button className={`dorm-save ${saved.includes(item.id) ? 'is-saved' : ''}`} aria-label={`${saved.includes(item.id) ? 'Unsave' : 'Save'} ${item.title}`} aria-pressed={saved.includes(item.id)} onClick={() => toggleSave(item.id)}><Heart size={19} fill={saved.includes(item.id) ? 'currentColor' : 'none'} /></button></div><div className="dorm-product-info"><div className="dorm-product-price price-row"><strong>{price(item.price)}</strong><span><Heart size={14} />{(item.likes || 0) + (saved.includes(item.id) ? 1 : 0)}</span></div><button className="dorm-product-title" onClick={() => openDetail(item)}>{item.title}</button><div className="dorm-seller"><span style={{ background: item.color }}>{item.initials?.slice(0, 1)}</span><div><strong>{item.seller}</strong><small>{item.campus || 'Virginia Tech'}</small></div></div></div></article>;
}

export default function Marketplace({ page, category, search, filtered, saved, toggleSave, openDetail, openSell, setModal, sort, setSort, maxPrice, setMaxPrice, condition, setCondition, onCategory }) {
  const arrivals = useRef(null);
  const isHome = page === 'Explore' && category === 'All finds' && !search && maxPrice === 10000 && condition === 'Any condition' && sort === 'recommended';
  const jumpToDeals = () => document.getElementById('finds')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  const card = item => <ProductCard key={item.id} {...{ item, saved, toggleSave, openDetail }} />;
  const newest = filtered.filter(item => item.collection === 'new' || item.own);
  const trending = filtered.filter(item => item.collection !== 'new' && !item.own);
  return <>
    {isHome && <><section className="dorm-container dorm-hero-wrap"><div className="dorm-hero"><div className="dorm-hero-copy"><span className="dorm-pill">🎒 VIRGINIA TECH STUDENT MARKETPLACE</span><h1>Buy & sell with peers,<br />right at Virginia Tech.</h1><p>No shipping costs. No sketchy meetups. Just Hokies exchanging good stuff from textbooks to full bento kitchen units.</p><div className="dorm-hero-buttons"><button className="primary" onClick={jumpToDeals}>Explore Deals</button><button className="secondary" onClick={() => setModal('help')}>How it Works</button></div></div><img className="dorm-hero-image" src={figmaImage('v13_59')} alt="Cozy student dorm with desks, books, plants and string lights" /></div></section><section className="dorm-trust"><div className="dorm-container"><div><span><ShieldCheck /></span><div><h3>A Student-First Community</h3><p>Built for Virginia Tech · demo profiles today</p></div></div><div><span><MapPin /></span><div><h3>Safe Campus Handovers</h3><p>Meet at designated campus spots or libraries</p></div></div><div><span><CheckCircle2 /></span><div><h3>No Hidden Fees</h3><p>Keep 100% of what you earn selling your gear</p></div></div></div></section></>}
    <section className="dorm-container dorm-listings-section" id="finds"><div className="dorm-section-heading"><div><h2>{page === 'Saved items' ? '💜 Your Saved Finds' : page === 'My listings' ? '🎒 Your Listings' : isHome ? '🔥 Trending on Campus' : category === 'All finds' ? '✨ All Campus Listings' : campusCategories.find(([value]) => value === category)?.[1]}</h2><p>{search ? `Results for “${search}”` : page === 'My listings' ? 'Give your pre-loved things their next chapter' : page === 'Saved items' ? 'All the good stuff you want to come back to' : 'Top requested items right now near you'}</p></div>{isHome ? <button className="dorm-link" onClick={() => setSort('popular')}>See All Trending <ArrowRight size={19} /></button> : page === 'My listings' ? <button className="primary" onClick={openSell}>+ Post Item</button> : null}</div>
      {!isHome && <div className="dorm-filters"><label>Sort by<select aria-label="Sort listings" value={sort} onChange={event => setSort(event.target.value)}><option value="recommended">Recommended</option><option value="new">Newest first</option><option value="popular">Most saved</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label><label>Maximum price ($)<input aria-label="Maximum price" type="number" min="0" max="10000" value={maxPrice} onChange={event => setMaxPrice(Number(event.target.value))} /></label><label>Condition<select value={condition} onChange={event => setCondition(event.target.value)}><option>Any condition</option><option>Like new</option><option>Good</option><option>Fair</option></select></label><button className="dorm-link" onClick={() => { setSort('recommended'); setMaxPrice(10000); setCondition('Any condition'); onCategory('All finds'); }}>Reset filters</button></div>}
      <div className="dorm-product-grid">{(isHome ? trending : filtered).map(card)}</div>{!filtered.length && <div className="empty-state"><Search size={36} /><h3>{page === 'My listings' ? 'Your first listing starts here.' : 'No finds here yet.'}</h3><p>{page === 'Saved items' ? 'Tap the heart on a listing to save it for later.' : 'Try another category or post something of your own.'}</p><button className="primary" onClick={page === 'My listings' ? openSell : () => { onCategory('All finds'); setSort('recommended'); setMaxPrice(10000); setCondition('Any condition'); }}>{page === 'My listings' ? 'Post your first item' : 'Explore all finds'}</button></div>}
    </section>
    {isHome && <><section className="dorm-arrivals"><div className="dorm-container"><div className="dorm-section-heading"><div><h2>✨ New Arrivals</h2><p>Fresh finds ready for their next home</p></div><button className="dorm-link" onClick={() => arrivals.current?.scrollBy({ left: 320, behavior: 'smooth' })}>Swipe for More <ArrowRight size={19} /></button></div><div className="dorm-arrivals-track" ref={arrivals}>{newest.map(card)}{!newest.length && <p>No new arrivals just yet. Check back soon.</p>}</div></div></section>
    <section className="dorm-container dorm-spotlight"><div className="dorm-section-heading"><div><h2>🤝 Student Seller Spotlight</h2><p>Meet the campus thrifters keeping student life circular and affordable</p></div></div><div className="dorm-spotlight-grid"><article><span className="dorm-pill">💡 FEATURED SHOP</span><h3>Sofia’s Thrift Haven</h3><blockquote>“I specialize in vintage clothing and curated study materials. Everything I sell is pre-loved, carefully cleaned, and delivered right inside your dorm lobby!”</blockquote><div className="dorm-spotlight-footer"><div className="dorm-featured-person"><img src={figmaImage('v13_414')} alt="Sofia Ramirez" /><div><strong>Sofia Ramirez</strong><small>VT · Featured demo seller</small></div></div><button className="primary" onClick={() => setModal('shop')}>Visit Shop</button></div></article><article><span className="dorm-pill">🎓 CAMPUS ORG INITIATIVE</span><h3>Hokie Sustainability Hub</h3><blockquote>“We partner with Dorm.io to coordinate massive donation run sales at the end of each semester. All proceeds support local green campus efforts!”</blockquote><div className="dorm-spotlight-footer"><div className="dorm-featured-person"><span><Leaf size={27} /></span><div><strong>Hokie Sustainability Hub</strong><small>Virginia Tech · Student Club Org</small></div></div><button className="primary" onClick={() => setModal('ecohub')}>Learn More</button></div></article></div></section>
    <section className="dorm-container dorm-app-section"><div className="dorm-app-banner"><div><h2>Get real-time updates<br />on the Dorm.io app</h2><p>Enable push notifications for instant deal alerts when top-reviewed sellers near your dorm post new textbooks or essentials.</p><div className="dorm-store-buttons"><button onClick={() => setModal('app')}><Smartphone size={22} /> App Store</button><button onClick={() => setModal('app')}><span className="play-triangle">▷</span> Google Play</button></div></div><img src={figmaImage('v13_454')} alt="Dorm.io mobile app concept" /></div></section></>}
  </>;
}

export function SiteFooter({ navigate, onCategory, setModal }) {
  return <footer className="dorm-footer"><div className="dorm-container"><div className="dorm-footer-columns"><div><Brand onClick={() => navigate('Explore')} /><p>The Virginia Tech student marketplace designed for seamless exchanges, sustainable circular student living, and making good deals closer to home.</p></div><div><h3>Marketplace</h3><button onClick={() => onCategory('All finds')}>All Listings</button><button onClick={() => onCategory('Furniture')}>Dorm Deco</button><button onClick={() => onCategory('Textbooks')}>Textbooks</button><button onClick={() => onCategory('Free Stuff')}>Campus Free Cycle</button></div><div><h3>Trust & Safety</h3>{['EDU Verification', 'Community Standards', 'Safety Safe Zones', 'Report Listing'].map(label => <button key={label} onClick={() => setModal('help')}>{label}</button>)}</div><div><h3>Company</h3>{['About Dorm.io', 'Student Careers', 'Contact Support', 'Brand Assets'].map(label => <button key={label} onClick={() => setModal('about')}>{label}</button>)}</div></div><div className="dorm-footer-bottom"><span>© {new Date().getFullYear()} Dorm.io. All student rights reserved.</span><div><button onClick={() => setModal('privacy')}>Privacy Policy</button><button onClick={() => setModal('terms')}>Terms of Use</button><button onClick={() => setModal('help')}>Trust Shield</button></div></div></div></footer>;
}
