import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';

test('marketplace browsing, saved items, messaging, checkout, and persistence', async () => {
  const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', { url: 'http://localhost' });
  for (const key of ['window', 'document', 'navigator', 'localStorage', 'HTMLElement', 'Event', 'MouseEvent', 'FormData', 'FileReader']) {
    Object.defineProperty(globalThis, key, { value: dom.window[key], configurable: true });
  }
  const apiCalls = [];
  Object.defineProperty(globalThis, 'fetch', { value: async (url, options = {}) => {
    apiCalls.push({ url, options });
    if (options.method === 'POST') return Response.json({ testMode: true, provider: 'venmo', account: { id: 'account-1', nickname: 'Dorm.io demo wallet', balance: 525 } }, { status: 201 });
    return Response.json({ account: { id: 'account-1', nickname: 'Dorm.io demo wallet', balance: 500 } });
  }, configurable: true });
  globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  const { createElement, act } = await import('react');
  const { createRoot } = await import('react-dom/client');
  const server = await createServer({ server: { middlewareMode: true, watch: null }, optimizeDeps: { noDiscovery: true, include: [] }, appType: 'custom' });
  let root;
  try {
    const { default: App } = await server.ssrLoadModule('/src/App.jsx');
    root = createRoot(document.getElementById('root'));
    await act(async () => root.render(createElement(App)));
    const click = async selector => {
      const element = document.querySelector(selector);
      assert.ok(element, `Expected element: ${selector}`);
      await act(async () => element.click());
    };
    const button = async label => {
      const element = [...document.querySelectorAll('button')].find(el => el.textContent.trim() === label);
      assert.ok(element, `Expected button: ${label}`);
      await act(async () => element.click());
    };
    const type = async (selector, value) => {
      const element = document.querySelector(selector);
      assert.ok(element);
      await act(async () => {
        const prototype = element.tagName === 'TEXTAREA' ? dom.window.HTMLTextAreaElement.prototype : dom.window.HTMLInputElement.prototype;
        Object.getOwnPropertyDescriptor(prototype, 'value').set.call(element, value);
        element.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
      });
    };
    assert.equal(document.querySelectorAll('.product-card').length, 13);
    assert.equal(document.querySelectorAll('.dorm-arrivals-track .product-card').length, 5);
    assert.equal(document.querySelectorAll('.dorm-product-grid .product-card').length, 8);
    assert.ok([...document.querySelectorAll('img')].every(img => img.getAttribute('src')?.includes('/assets/images/')));
    await click('[aria-label="Switch to dark mode"]');
    assert.equal(document.documentElement.dataset.theme, 'dark');
    assert.equal(JSON.parse(localStorage.getItem('dormio-theme')), 'dark');
    const originalAvatar = document.querySelector('.dorm-user img').src;
    await click('[aria-label="Open profile settings"]');
    assert.equal(document.querySelector('.account-photo-row img').src, originalAvatar);
    await type('[name="name"]', 'Alex Rivera');
    assert.equal(document.querySelector('[name="campus"]').value, 'Virginia Tech');
    assert.equal(document.querySelector('[name="campus"]').readOnly, true);
    await type('[name="pickup"]', 'Newman Library');
    await type('[name="bio"]', 'Textbooks and vintage finds.');
    const profilePhoto = document.querySelector('[aria-label="Change profile photo"]');
    Object.defineProperty(profilePhoto, 'files', { value: [new dom.window.File([new Uint8Array([137, 80, 78, 71])], 'avatar.png', { type: 'image/png' })] });
    await act(async () => { profilePhoto.dispatchEvent(new dom.window.Event('change', { bubbles: true })); await new Promise(resolve => setTimeout(resolve, 50)); });
    await button('Save changes');
    assert.match(document.querySelector('.dorm-user').textContent, /Alex Rivera/);
    assert.match(document.querySelector('.dorm-user img').src, /^data:image\/png;base64,/);
    assert.equal(JSON.parse(localStorage.getItem('dormio-profile')).pickup, 'Newman Library');
    await click('[aria-label="Open profile settings"]');
    assert.equal(document.querySelector('.account-photo-row img').src, document.querySelector('.dorm-user img').src);
    await type('[name="name"]', 'Unsaved edit');
    await button('Cancel');
    assert.match(document.querySelector('.dorm-user').textContent, /Alex Rivera/);
    await button('App Store');
    assert.match(document.querySelector('[role="dialog"]').textContent, /coming soon/);
    await click('[aria-label="Close dialog"]');
    await button('Visit Shop');
    assert.match(document.querySelector('[role="dialog"]').textContent, /Sofia/);
    await click('[aria-label="Close dialog"]');
    await button('📚 Textbooks');
    assert.equal(document.querySelectorAll('.product-card').length, 1);
    await button('⚡️ All Campus');
    await type('input[aria-label="Search marketplace"]', 'Sony');
    assert.equal(document.querySelectorAll('.product-card').length, 1);
    await click('[aria-label="Clear search"]');
    await click('[aria-label="Save Mini Fridge (Super Clean, Works Perfect)"]');
    assert.deepEqual(JSON.parse(localStorage.getItem('dormio-v1-saved')), [1]);
    await click('.dorm-account-nav button:nth-child(2)');
    assert.equal(document.querySelectorAll('.product-card').length, 1);
    await click('[aria-label="View Mini Fridge (Super Clean, Works Perfect)"]');
    await button('Message seller');
    await button('Is this still available?');
    await click('[aria-label="Send message"]');
    assert.match(document.querySelector('.message-bubble').textContent, /Is this still available/);
    assert.equal(JSON.parse(localStorage.getItem('dormio-v1-messages')).length, 1);
    await button('View listing');
    await button('Make it yours');
    assert.match(document.querySelector('.payment-method').textContent, /\$500/);
    await button('Pay $45');
    assert.match(document.querySelector('[role="dialog"]').textContent, /Good find. It’s yours!/);
    const transactions = JSON.parse(localStorage.getItem('dormio-v1-transactions'));
    assert.equal(transactions.length, 1);
    assert.equal(transactions[0].amount, 45);
    await button('View wallet activity');
    assert.match(document.querySelector('.wallet-card').textContent, /\$455/);
    await button('Explore');
    assert.equal(document.querySelectorAll('.product-card').length, 12);
    assert.equal(document.querySelector('[aria-label="View Mini Fridge (Super Clean, Works Perfect)"]'), null);
    localStorage.setItem('dormio-profile', JSON.stringify({ ...JSON.parse(localStorage.getItem('dormio-profile')), campus: 'Old campus' }));
    localStorage.setItem('dormio-v1-listings', JSON.stringify(JSON.parse(localStorage.getItem('dormio-v1-listings')).map(item => ({ ...item, campus: 'Old campus', image: undefined }))));
    await act(async () => root.unmount());
    root = createRoot(document.getElementById('root'));
    await act(async () => root.render(createElement(App)));
    assert.equal(document.querySelectorAll('.product-card').length, 12, 'purchased listings stay removed after remount');
    assert.ok([...document.querySelectorAll('.dorm-seller small')].every(label => label.textContent === 'Virginia Tech'));
    assert.equal(JSON.parse(localStorage.getItem('dormio-profile')).campus, 'Virginia Tech');
    assert.ok(JSON.parse(localStorage.getItem('dormio-v1-listings')).every(item => item.campus === 'Virginia Tech'));
    assert.ok([...document.querySelectorAll('.product-card img')].every(img => img.getAttribute('src')?.includes('/assets/images/')), 'missing persisted images are repaired');
    assert.equal(document.documentElement.dataset.theme, 'dark', 'theme persists after remount');
    assert.match(document.querySelector('.dorm-user').textContent, /Alex Rivera/, 'profile persists after remount');
    await click('[aria-label="Switch to light mode"]');
    assert.equal(document.documentElement.dataset.theme, 'light');
    await button('My wallet');
    assert.match(document.querySelector('.wallet-card').textContent, /\$455/, 'wallet balance persists');
    await button('+ Post Item');
    await type('[name="title"]', 'Desk lamp for a new semester');
    await type('[name="price"]', '18.50');
    await type('[name="description"]', 'A gently used lamp, available for pickup at the library.');
    await button('Publish listing');
    assert.match(document.querySelector('[role="alert"]').textContent, /Add a photo/);
    const fileInput = document.querySelector('input[type="file"]');
    const file = new dom.window.File([new Uint8Array([137, 80, 78, 71])], 'lamp.png', { type: 'image/png' });
    Object.defineProperty(fileInput, 'files', { value: [file] });
    await act(async () => {
      fileInput.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
      await new Promise(resolve => setTimeout(resolve, 50));
    });
    assert.ok(document.querySelector('[alt="Listing preview"]'));
    await button('Publish listing');
    assert.equal(document.querySelectorAll('.product-card').length, 1);
    assert.match(document.querySelector('.product-card').textContent, /Desk lamp for a new semester/);
    assert.match(document.querySelector('.price-row').textContent, /\$18.5/);
    assert.ok(JSON.parse(localStorage.getItem('dormio-v1-listings')).some(item => item.own && item.price === 18.5));
    await click('[aria-label="View Desk lamp for a new semester"]');
    await button('Remove your listing');
    assert.equal(document.querySelectorAll('.product-card').length, 0);
    await button('My wallet');
    assert.equal(document.querySelectorAll('.provider-card').length, 6);
    await button('Connect Stripe');
    assert.match(document.querySelector('[role="dialog"]').textContent, /Not connected/);
    await button('Back to wallet');
    await click('[aria-label="Prefer Stripe"]');
    await button('Explore');
    await click('[aria-label="View M1 MacBook Air 8GB/256GB Space Gray"]');
    await button('Make it yours');
    assert.ok([...document.querySelectorAll('button')].find(el => el.textContent === 'Stripe integration required').disabled);
    await click('[aria-label="Close dialog"]');
    for (const [method, label] of [['cash', 'Cash at pickup'], ['venmo', 'Venmo'], ['paypal', 'PayPal'], ['cashapp', 'Cash App']]) {
      await button('My wallet');
      await click(`[aria-label="Prefer ${label}"]`);
      assert.equal(JSON.parse(localStorage.getItem('dormio-payments')).preferred, method);
      await button('Explore');
      await click('[aria-label="View M1 MacBook Air 8GB/256GB Space Gray"]');
      await button('Make it yours');
      assert.ok(document.querySelector(`input[name="checkout-method"][value="${method}"]`).checked);
      await button(method === 'cash' ? 'Reserve · Pay cash at pickup' : `Reserve · Pay with ${label}`);
      assert.match(document.querySelector('[role="dialog"]').textContent, /No money has moved/);
      assert.equal(JSON.parse(localStorage.getItem('dormio-v1-transactions'))[0].status, 'pending');
      await button('View wallet activity');
      assert.match(document.querySelector('.wallet-card').textContent, /\$455/);
      await button('Cancel reservation');
      assert.equal(JSON.parse(localStorage.getItem('dormio-v1-transactions'))[0].status, 'cancelled');
      assert.equal(JSON.parse(localStorage.getItem('dormio-v1-listings')).find(item => item.id === 2).sold, false);
    }
    await button('Add test credits');
    await click('input[name="deposit-provider"][value="venmo"]');
    await button('Add $25 with test Venmo');
    await act(async () => new Promise(resolve => setTimeout(resolve, 10)));
    assert.match(document.querySelector('.wallet-card').textContent, /\$480/);
    assert.match(document.querySelector('.deposit-activity').textContent, /Test credits deposited/);
    const depositCall = apiCalls.find(call => call.options.method === 'POST');
    assert.equal(depositCall.url, '/api/wallet/deposits');
    const depositBody = JSON.parse(depositCall.options.body);
    assert.equal(depositBody.amount, 25);
    assert.equal(depositBody.provider, 'venmo');
    assert.match(depositBody.checkoutId, /^test_[a-z0-9]{32}$/);
  } finally {
    if (root) await act(async () => root.unmount());
    await server.close();
    dom.window.close();
  }
});
