import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, BadgeCheck, Bell, BookOpen, Check, CheckCheck, ChevronRight, CreditCard, GraduationCap, Grid2X2, Heart, HelpCircle, Leaf, MapPin, Menu, MessageCircle, Plus, Search, Send, ShieldCheck, ShoppingBag, SlidersHorizontal, Sofa, Sparkles, Tag, Wallet, X, Headphones, Shirt, Lamp } from 'lucide-react';
import { initialListings, photo } from './data';

function useStored(key, fallback) {
  const [value, setValue] = useState(() => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } });
  useEffect(() => { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* Keep the session usable when browser storage is full or unavailable. */ } }, [key, value]);
  return [value, setValue];
}
const categories = [['All finds', Grid2X2], ['Textbooks', BookOpen], ['Furniture', Sofa], ['Electronics', Headphones], ['Dorm essentials', Lamp], ['Clothing & more', Shirt]];
const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(value);

export default function App() {
  const [page, setPage] = useState('Explore');
  const [category, setCategory] = useState('All finds');
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState('recommended');
  const [saved, setSaved] = useStored('loop-saved', []);
  const [listings, setListings] = useStored('loop-listings', initialListings);
  const [transactions, setTransactions] = useStored('loop-transactions', []);
  const [messages, setMessages] = useStored('loop-messages', []);
  const [modal, setModal] = useState(null);
  const [selected, setSelected] = useState(null);
  const [toast, setToast] = useState('');
  const [maxPrice, setMaxPrice] = useState(10000);
  const [condition, setCondition] = useState('Any condition');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [activeChat, setActiveChat] = useState(null);
  const [messageText, setMessageText] = useState('');
  const [paymentDone, setPaymentDone] = useState(false);
  const [formError, setFormError] = useState('');
  const [imagePreview, setImagePreview] = useState('');
  const balance = 500 - transactions.reduce((sum, tx) => sum + tx.amount, 0);
  const toastTimer = useRef();
  const showToast = text => { setToast(text); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 3500); };
  const navigate = next => { setPage(next); setMobileNav(false); setSearch(''); setCategory('All finds'); };
  const toggleSave = id => setSaved(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const openDetail = item => { setSelected(item); setPaymentDone(false); setFormError(''); setModal('detail'); };
  const openSell = () => { setImagePreview(''); setFormError(''); setModal('sell'); };
  const closeModal = () => { setModal(null); setFormError(''); };
  useEffect(() => {
    if (!modal) return;
    const previous = document.activeElement;
    const dialog = document.querySelector('[role="dialog"]');
    const elements = () => [...dialog.querySelectorAll('button, input, select, textarea, [tabindex="0"]')].filter(el => !el.disabled);
    elements()[0]?.focus();
    const onKey = e => {
      if (e.key === 'Escape') setModal(null);
      if (e.key === 'Tab') { const focusable = elements(); const first = focusable[0]; const last = focusable.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }
    };
    document.addEventListener('keydown', onKey); document.body.style.overflow = 'hidden';
    return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = ''; previous?.focus(); };
  }, [modal]);
  const startChat = item => { setActiveChat(item); setModal(null); navigate('Messages'); };
  const submitMessage = e => { e.preventDefault(); if (!messageText.trim() || !activeChat) return; setMessages(current => [...current, { id: Date.now(), listingId: activeChat.id, text: messageText.trim(), time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }]); setMessageText(''); };
  const buyItem = () => {
    if (selected.price > balance) { setFormError('Your demo wallet does not have enough funds for this purchase.'); return; }
    if (transactions.some(tx => tx.listingId === selected.id)) return;
    setTransactions(current => [{ id: `LP-${Date.now().toString().slice(-7)}`, listingId: selected.id, title: selected.title, seller: selected.seller, amount: selected.price, date: new Date().toISOString() }, ...current]);
    setListings(current => current.map(item => item.id === selected.id ? { ...item, sold: true } : item)); setPaymentDone(true);
  };
  const submitListing = e => {
    e.preventDefault(); const data = new FormData(e.currentTarget); const price = Number(data.get('price'));
    if (!imagePreview) { setFormError('Add a photo so other students can see your item.'); return; }
    if (!Number.isFinite(price) || price <= 0 || price > 10000) { setFormError('Please enter a price between $0.01 and $10,000.'); return; }
    setListings(current => [{ id: Date.now(), title: data.get('title').trim(), price, category: data.get('category'), condition: data.get('condition'), description: data.get('description').trim(), image: imagePreview, location: 'On campus', seller: 'You', initials: 'AT', color: '#eaded3', age: 0, own: true }, ...current]);
    closeModal(); navigate('My listings'); showToast('Your listing is live. Welcome to the loop!');
  };
  const uploadImage = e => { const file = e.target.files[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setFormError('Choose a JPG, PNG, or WebP image.'); return; } if (file.size > 2000000) { setFormError('Choose an image smaller than 2 MB.'); return; } const reader = new FileReader(); reader.onload = () => { setImagePreview(reader.result); setFormError(''); }; reader.readAsDataURL(file); };
  const filtered = listings.filter(item => !item.sold && (page !== 'Saved items' || saved.includes(item.id)) && (page !== 'My listings' || item.own) && (category === 'All finds' || item.category === category) && `${item.title} ${item.category}`.toLowerCase().includes(search.toLowerCase()) && item.price <= maxPrice && (condition === 'Any condition' || item.condition === condition)).sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : sort === 'new' ? a.age - b.age : 0);
  const nav = [['Explore', Grid2X2], ['Saved items', Heart], ['Messages', MessageCircle], ['My listings', Tag], ['My wallet', Wallet]];
  const chatItems = listings.filter(item => messages.some(m => m.listingId === item.id) || item.id === activeChat?.id);

  return <div className="app-shell">
    {mobileNav && <div className="nav-scrim" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'is-open' : ''}`}>
      <a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('Explore'); }}><span className="brand-mark">↻</span>loop<span className="brand-dot">.</span></a>
      <div className="campus-switch"><span className="campus-icon"><GraduationCap size={20} /></span><div><strong>Virginia Tech</strong><span>Your campus community</span></div><BadgeCheck size={16} className="campus-check" /></div>
      <div className="nav-label">YOUR LITTLE CORNER</div>
      <nav>{nav.map(([name, Icon]) => <button key={name} className={`nav-item ${page === name ? 'active' : ''}`} onClick={() => navigate(name)}><Icon size={19} /><span>{name}</span>{name === 'Saved items' && saved.length > 0 && <span className="nav-count">{saved.length}</span>}{name === 'Explore' && <span className="active-dot" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="give-card"><span className="give-icon"><Leaf size={22} /></span><strong>Good finds. Less footprint.</strong><p>A second home for your stuff.<br />A little better for the planet.</p><button onClick={openSell}>Keep it in the loop <ArrowUpRight size={16} /></button></div><button className="help-link" onClick={() => setModal('help')}><HelpCircle size={18} /> Help & community</button><button className="profile" onClick={() => setModal('profile')}><span className="avatar profile-avatar">AT</span><span><strong>Aditya</strong><small>Virginia Tech student</small></span><ChevronRight size={17} /></button></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="Open menu" onClick={() => setMobileNav(true)}><Menu /></button><span>Marketplace</span><ChevronRight size={14} /><strong>{page}</strong></div><div className="topbar-actions"><span className="campus-location"><MapPin size={15} /> Blacksburg, VA</span><span className="topbar-divider" /><button className="icon-button notification-button" aria-label="Notifications" onClick={() => setModal('notifications')}><Bell size={20} /><i /></button><button className="primary sell-top" onClick={openSell}><Plus size={17} /> Sell an item</button></div></header>
      <main>
        {(page === 'Explore' || page === 'Saved items' || page === 'My listings') && <>
          <div className="page-heading"><div><div className="eyebrow"><span /> THE CAMPUS CIRCULAR</div><h1>{page === 'Explore' ? 'Big finds. Student prices.' : page === 'Saved items' ? 'The ones you have your eye on.' : 'Your stuff. Its next chapter.'}</h1><p>{page === 'Explore' ? 'From one student to another. Find what you need, pass on what you don’t.' : page === 'Saved items' ? 'All your favorite finds, in one happy place.' : 'Make a little space. Make a little extra. Keep it in the community.'}</p></div><span className="semester-tag"><Sparkles size={15} /> New semester, new finds</span></div>
          {page === 'Explore' && <section className="hero"><div className="hero-copy"><span className="hero-kicker"><span /> LESS SPENDING. MORE LIVING.</span><h2>Your next chapter.<br />Someone else’s <em>pre-loved.</em></h2><p>Textbooks, cozy corners, and everything in between.<br className="desktop-break" /> Great things deserve another semester.</p><button className="dark-button" onClick={() => { setCategory('All finds'); document.getElementById('finds').scrollIntoView({ behavior: 'smooth', block: 'start' }); }}>Find your next favorite <ArrowRight size={17} /></button><div className="hero-social"><div className="avatar-stack"><img src={photo('photo-1534528741775-53994a69daeb', 70)} alt="" /><img src={photo('photo-1500648767791-00dcc994a43e', 70)} alt="" /><img src={photo('photo-1506794778202-cad84cf45f1d', 70)} alt="" /><span>+2k</span></div><span>A little community. A lot of good finds.</span></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="hero-spark spark-one">✳</span><span className="hero-spark spark-two">✦</span><div className="hero-photo"><img src={photo('photo-1493663284031-b7e3aefcae8e', 1000)} alt="A cozy student living space with a sofa and plants" /></div><div className="floating-label second-life"><Leaf size={17} /> A second life looks good.</div><div className="floating-label find-label"><span className="find-icon"><Heart size={19} /></span><div><strong>Pre-loved. Re-loved.</strong><span>Made for your next chapter.</span></div></div><span className="image-caption">GOOD FOR YOUR SPACE. GREAT FOR YOUR WALLET.</span></div></section>}
          <div className="trust-strip"><span><BadgeCheck size={17} /><strong>Your campus, your people</strong><span>Student-to-student connections</span></span><span><ShieldCheck size={17} /><strong>Simple, secure checkout</strong><span>Powered by Nessie · Demo</span></span><span><Leaf size={17} /><strong>Small swaps. Big impact.</strong><span>Keep good things going</span></span></div>
          <section className="browse-section" id="finds"><div className="browse-heading"><div><h2>{page === 'Explore' ? 'Fresh finds around campus' : page === 'Saved items' ? 'Your saved finds' : 'Your active listings'} <span>{filtered.length}</span></h2><p>{page === 'Explore' ? 'Your next “wait, that’s such a good deal” is right here.' : 'A little less scrolling. A little more finding.'}</p></div><label className="sort-label">Sort by: <select aria-label="Sort listings" value={sort} onChange={e => setSort(e.target.value)}><option value="recommended">Recommended</option><option value="new">Newest first</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>
          <div className="search-row"><label className="search-box"><Search size={19} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search textbooks, furniture, and little life upgrades..." aria-label="Search marketplace" />{search && <button className="icon-button" aria-label="Clear search" onClick={() => setSearch('')}><X size={15} /></button>}<span className="search-shortcut">Find your thing</span></label><button className={`filter-button ${filtersOpen ? 'selected' : ''}`} onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={17} /> Filters {(maxPrice < 10000 || condition !== 'Any condition') && <span className="active-dot" />}</button></div>
          {filtersOpen && <div className="filter-panel"><label>Maximum price: {money(maxPrice)}<input type="range" min="0" max="10000" step="10" value={maxPrice} onChange={e => setMaxPrice(Number(e.target.value))} /></label><label>Condition<select value={condition} onChange={e => setCondition(e.target.value)}><option>Any condition</option><option>Like new</option><option>Good</option><option>Fair</option></select></label><button className="text-button" onClick={() => { setMaxPrice(10000); setCondition('Any condition'); }}>Reset filters</button></div>}
          <div className="category-row">{categories.map(([name, Icon]) => <button key={name} className={`category ${category === name ? 'selected' : ''}`} onClick={() => setCategory(name)}><Icon size={16} />{name}</button>)}</div>
          <div className="product-grid">{filtered.map(item => <article className="product-card" key={item.id}><div className="product-image-wrap"><button className="product-image-button" onClick={() => openDetail(item)} aria-label={`View ${item.title}`}><img src={item.image} alt={item.title} loading="lazy" /></button>{item.badge && <span className={`product-badge ${item.badge === 'Great deal' ? 'green' : ''}`}>{item.badge === 'Great deal' ? <Tag size={11} /> : <Sparkles size={11} />}{item.badge}</span>}<button className={`save-button ${saved.includes(item.id) ? 'saved' : ''}`} aria-label={`${saved.includes(item.id) ? 'Unsave' : 'Save'} ${item.title}`} aria-pressed={saved.includes(item.id)} onClick={() => toggleSave(item.id)}><Heart size={17} fill={saved.includes(item.id) ? 'currentColor' : 'none'} /></button><span className="condition-badge"><span />{item.condition}</span></div><div className="product-info"><div className="product-category">{item.category}</div><button className="product-title" onClick={() => openDetail(item)}>{item.title}</button><div className="price-row"><strong>{money(item.price)}</strong>{item.original && <del>{money(item.original)}</del>}<span><MapPin size={12} /> {item.location}</span></div><div className="seller-row"><span className="avatar" style={{ background: item.color }}>{item.initials}</span><span>{item.seller}</span><BadgeCheck size={13} /><span className="seller-campus">Virginia Tech</span></div></div></article>)}</div>
          {!filtered.length && <div className="empty-state"><ShoppingBag size={36} /><h3>{page === 'Saved items' ? 'Your next favorite is out there.' : page === 'My listings' ? 'Give something good a second life.' : 'No finds just yet.'}</h3><p>{page === 'Saved items' ? 'Tap the heart on any listing to keep it here.' : page === 'My listings' ? 'Your first listing is only a few details away.' : 'Try a different search or reset your filters.'}</p><button className="primary" onClick={() => { if (page === 'My listings') openSell(); else { navigate('Explore'); setMaxPrice(10000); setCondition('Any condition'); } }}>{page === 'My listings' ? 'Create a listing' : 'Explore all finds'}<ArrowRight size={16} /></button></div>}
          </section><div className="bottom-note"><span className="mini-brand">↻</span><p>Good things come around.<span> Thanks for keeping them in the loop.</span></p><Leaf size={16} /></div>
        </>}
        {page === 'My wallet' && <><div className="page-heading"><div><div className="eyebrow"><span /> A LITTLE PEACE OF MIND</div><h1>Your campus wallet.</h1><p>Keep track of your finds and every little saving.</p></div><span className="semester-tag">Nessie sandbox simulation</span></div><div className="wallet-layout"><div className="wallet-card"><span><Wallet size={22} /> Loop wallet</span><p>Available demo balance</p><h2>{money(balance)}</h2><div><span>Aditya · Student account</span><span>•••• 2048</span></div></div><div className="wallet-explainer"><ShieldCheck size={27} /><h3>A simple way to settle up.</h3><p>This prototype simulates a customer account, campus merchants, and purchase transactions inspired by Capital One’s Nessie API.</p><span className="demo-note">Demo funds only. No real money moves.</span></div></div><section className="panel"><h2>Recent activity <span className="count-pill">{transactions.length}</span></h2>{transactions.length ? transactions.map(tx => <div className="transaction" key={tx.id}><span className="transaction-icon"><ArrowUpRight size={22} /></span><div><strong>{tx.title}</strong><small>{tx.seller} · {new Date(tx.date).toLocaleDateString()} · {tx.id}</small></div><strong>−{money(tx.amount)}</strong><span className="status-pill">Completed</span></div>) : <div className="empty-state"><CreditCard size={35} /><h3>Your next good find starts here.</h3><p>You have $500 in demo funds to try a purchase.</p><button className="primary" onClick={() => navigate('Explore')}>Explore the marketplace <ArrowRight size={16} /></button></div>}</section></>}
        {page === 'Messages' && <><div className="page-heading"><div><div className="eyebrow"><span /> MAKE A CAMPUS CONNECTION</div><h1>A good find starts with hello.</h1><p>Ask a question, arrange a pickup, and keep the conversation going.</p></div></div><div className="messages-layout"><aside className="chat-list"><h3>Your conversations</h3>{chatItems.length ? chatItems.map(item => <button className={activeChat?.id === item.id ? 'active' : ''} onClick={() => setActiveChat(item)} key={item.id}><span className="avatar" style={{ background: item.color }}>{item.initials}</span><span><strong>{item.seller}</strong><small>{item.title}</small></span><ChevronRight size={15} /></button>) : <p>Message a seller from a listing to start a conversation.</p>}</aside><section className="chat-panel">{activeChat ? <><div className="chat-header"><img src={activeChat.image} alt="" /><div><strong>{activeChat.seller}</strong><small>{activeChat.title} · {money(activeChat.price)}</small></div><button className="text-button" onClick={() => openDetail(activeChat)}>View listing</button></div><div className="chat-messages"><div className="chat-demo"><ShieldCheck size={16} /> Demo conversation · Messages are saved on this device.</div>{messages.filter(m => m.listingId === activeChat.id).map(m => <div className="message-bubble" key={m.id}>{m.text}<small>{m.time}<CheckCheck size={13} /></small></div>)}{!messages.some(m => m.listingId === activeChat.id) && <div className="chat-starter"><MessageCircle size={32} /><p>Say hello to {activeChat.seller.split(' ')[0]}.</p><button onClick={() => setMessageText('Hi! Is this still available? I can pick it up on campus.')} className="category">Is this still available?</button></div>}</div><form onSubmit={submitMessage} className="message-form"><input aria-label="Your message" placeholder="Write a friendly hello..." value={messageText} onChange={e => setMessageText(e.target.value)} maxLength={2000} /><button className="primary" aria-label="Send message" disabled={!messageText.trim()}><Send size={18} /></button></form></> : <div className="empty-state"><MessageCircle size={40} /><h3>Your people are right around the corner.</h3><p>Choose a conversation, or find something you love.</p><button className="primary" onClick={() => navigate('Explore')}>Find something good <ArrowRight size={16} /></button></div>}</section></div></>}
      </main><footer><span>© {new Date().getFullYear()} Loop. Made for campus life.</span><span>Built on community. Powered by possibility. <span className="footer-flower">✳</span></span></footer>
    </div>
    {toast && <div className="toast" role="status"><Check size={18} />{toast}</div>}
    {modal && <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) closeModal(); }}><section role="dialog" aria-modal="true" aria-labelledby="modal-title" className={`modal ${modal === 'detail' ? 'detail-modal' : ''}`}><button className="modal-close icon-button" onClick={closeModal} aria-label="Close dialog"><X size={21} /></button>
      {modal === 'detail' && selected && <><div className="detail-image"><img src={selected.image} alt={selected.title} /></div><div className="detail-content"><div className="eyebrow">{selected.category} · {selected.condition}</div><h2 id="modal-title">{selected.title}</h2><div className="detail-price">{money(selected.price)} {selected.original && <del>{money(selected.original)}</del>}</div><p>{selected.description}</p><div className="detail-seller"><span className="avatar" style={{ background: selected.color }}>{selected.initials}</span><div><strong>{selected.seller} <BadgeCheck size={14} /></strong><small>Virginia Tech · {selected.location}</small></div></div><div className="pickup-note"><MapPin size={18} /><span>Meet nearby, keep it simple.<small>Arrange a public campus pickup with the seller.</small></span></div>{selected.sold || transactions.some(tx => tx.listingId === selected.id) ? <div className="status-pill">This find has a new home.</div> : selected.own ? <button className="secondary full-width" onClick={() => { setListings(current => current.filter(item => item.id !== selected.id)); closeModal(); showToast('Listing removed.'); }}>Remove your listing</button> : <><button className="primary full-width" onClick={() => { setModal('checkout'); setPaymentDone(false); }}>Make it yours <ArrowRight size={17} /></button><button className="secondary full-width" onClick={() => startChat(selected)}><MessageCircle size={17} /> Message seller</button></>}<div className="checkout-note"><ShieldCheck size={13} /> Nessie-powered demo checkout</div></div></>}
      {modal === 'checkout' && (paymentDone ? <div className="success-content"><div className="success-icon"><Check size={36} /></div><div className="eyebrow">A NEW CHAPTER BEGINS</div><h2 id="modal-title">Good find. It’s yours!</h2><p>Your demo payment of {money(selected.price)} is complete. Message {selected.seller} to arrange a pickup.</p><div className="order-summary"><img src={selected.image} alt="" /><div><strong>{selected.title}</strong><span>Paid with Loop wallet</span></div><BadgeCheck size={23} /></div><button className="primary full-width" onClick={() => startChat(selected)}>Arrange a pickup <MessageCircle size={17} /></button><button className="text-button" onClick={() => { closeModal(); navigate('My wallet'); }}>View wallet activity</button></div> : <div className="modal-body"><div className="eyebrow">ONE MORE LITTLE STEP</div><h2 id="modal-title">Make a good find yours.</h2><p>Review your purchase and pay with your demo wallet.</p><div className="order-summary"><img src={selected.image} alt="" /><div><strong>{selected.title}</strong><span>Sold by {selected.seller}</span></div><strong>{money(selected.price)}</strong></div><div className="payment-method"><Wallet size={24} /><div><strong>Loop wallet</strong><small>Available balance: {money(balance)}</small></div><span className="radio-check"><Check size={12} /></span></div><div className="checkout-totals"><div><span>Item price</span><span>{money(selected.price)}</span></div><div><span>Campus pickup</span><span>Free</span></div><div className="total"><strong>Total</strong><strong>{money(selected.price)}</strong></div></div>{formError && <p className="form-error" role="alert">{formError}</p>}<button className="primary full-width" onClick={buyItem} disabled={selected.price > balance}><ShieldCheck size={17} />Pay {money(selected.price)}</button>{selected.price > balance && <p className="form-error">Insufficient demo funds for this purchase.</p>}<p className="checkout-note">Simulated Nessie transaction. No real money is charged.</p></div>)}
      {modal === 'sell' && <form className="modal-body sell-form" onSubmit={submitListing}><div className="eyebrow">PASS IT ON. MAKE SOMEONE’S DAY.</div><h2 id="modal-title">Give it a second chapter.</h2><p>A few details, one photo, and you’re in the loop.</p><label className={`upload-area ${imagePreview ? 'has-image' : ''}`}>{imagePreview ? <img src={imagePreview} alt="Listing preview" /> : <><Plus size={28} /><strong>Add your best photo</strong><span>JPG, PNG, or WebP · Up to 2 MB</span></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadImage} aria-label="Upload listing photo" /></label><label>What are you selling?<input name="title" required maxLength={70} placeholder="e.g. Your next favorite desk chair" /></label><div className="form-grid"><label>Category<select name="category">{categories.slice(1).map(([name]) => <option key={name}>{name}</option>)}</select></label><label>Condition<select name="condition"><option>Like new</option><option>Good</option><option>Fair</option></select></label></div><label>Price ($)<input name="price" type="number" min="0.01" max="10000" step="0.01" placeholder="25.00" required /></label><label>A little about your item<textarea name="description" required maxLength={1200} rows={3} placeholder="The details you’d want to know. Condition, size, pickup spot..." /></label>{formError && <p className="form-error" role="alert">{formError}</p>}<button className="primary full-width" type="submit">Publish listing <ArrowRight size={17} /></button><span className="checkout-note">Your listing is saved locally in this demo.</span></form>}
      {modal === 'help' && <div className="modal-body"><div className="eyebrow">GOOD NEIGHBORS. GOOD FINDS.</div><h2 id="modal-title">Welcome to the community.</h2><div className="help-item"><Search /><div><h3>Find your next favorite</h3><p>Browse by category, set a budget, or search for something specific. Save your favorites with the heart.</p></div></div><div className="help-item"><MessageCircle /><div><h3>Say hello, meet on campus</h3><p>Ask sellers about the item and agree on a public pickup spot, like the library or student center.</p></div></div><div className="help-item"><Wallet /><div><h3>Try your campus wallet</h3><p>Everyone starts with $500 in demo funds. Purchases update your balance and history on this device.</p></div></div><div className="help-item"><Leaf /><div><h3>Keep the good things going</h3><p>List items with honest descriptions and clear photos. A little care makes a better campus community.</p></div></div></div>}
      {modal === 'notifications' && <div className="modal-body"><div className="eyebrow">IN THE LOOP</div><h2 id="modal-title">Your campus updates.</h2><div className="help-item"><Sparkles /><div><h3>Welcome to Loop!</h3><p>Your campus marketplace is ready to explore. Find your next favorite or give something a second home.</p></div></div><div className="help-item"><Wallet /><div><h3>Your demo wallet is ready</h3><p>You have {money(balance)} to explore the simulated checkout experience.</p><button className="text-button" onClick={() => { closeModal(); navigate('My wallet'); }}>Open your wallet <ArrowRight size={15} /></button></div></div></div>}
      {modal === 'profile' && <div className="modal-body profile-modal"><span className="avatar profile-large">AT</span><h2 id="modal-title">Hey, Aditya.</h2><p>Your little corner of Virginia Tech.</p><div className="profile-details"><span><GraduationCap size={19} /> Virginia Tech student</span><span><MapPin size={19} /> Blacksburg, Virginia</span><span><ShieldCheck size={19} /> Demo student profile</span></div><button className="primary full-width" onClick={() => { closeModal(); navigate('My listings'); }}>Manage your listings <ArrowRight size={17} /></button><p className="checkout-note">This demo uses a local profile. Account verification is not connected.</p></div>}
    </section></div>}
  </div>;
}
